/*
 * This source file was generated by the Gradle 'init' task
 */
package qa.rest.screenplay.challenge.serenityJUnit5;

class TestGetUser {
    // Code temporarily commented out to avoid compilation errors on unused class
    /*
     * @Test void appHasAGreeting() {
     * App classUnderTest = new App();
     * assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
     * }
     */
}
